image: 192.168.3.1:5000/vterranz/discobuild

before_script:
  - export DOCKER_HOST=http://192.168.1.3:2375

stages:
  - build

build:
  stage: build
  script:
    - mkdir build && cd build && cmake .. && make -j
  artifacts:
    paths:
      - build/DiscoDiag