image: vterranz/discobuild:latest

before_script:
  - export DOCKER_HOST=http://192.168.1.3:2375

stages:
  - build

build:
  stage: build
  script:
    - sh mkdir build && cd build && cmake .. && make -j
